### ISSUE TITLE
notice : gcov_info struct is changed on GCC v12 

### ISSUE THREAD

**Issue by boger047** [nasa-jpl/embedded-gcov#7]
checksum added after gcc v12,  so if use this ,  need add checksum as below .
```struct gcov_info {
	gcov_unsigned_t version;
	struct gcov_info *next;
	gcov_unsigned_t stamp;
	**gcov_unsigned_t checksum;**
	const char *filename;
	gcov_merge_fn merge[GCOV_COUNTERS];
	unsigned n_functions;
	struct gcov_fn_info **functions;
};
```
https://github.com/nasa-jpl/embedded-gcov/blob/7cc670697d0b9fa23f7d22ed5f6776164d7732e2/code/gcov_gcc.c#L102C1-L110C3

**Comment by clnhlzmn** [comment]
Is there a reason a fix for this wasn't added to main?
